Repository Cusatelli/Case-Se-Java-MeFit, pull requests merged in 2022-03, with the labels that each got.

#34 request: development <- 25 api 03 user crud
  build.gradle
  src/main/java/com/noroff/mefit/controller/UserController.java
  src/main/java/com/noroff/mefit/model/User.java
  src/main/java/com/noroff/mefit/repository/UserRepository.java
  src/main/java/com/noroff/mefit/service/UserService.java
  src/main/resources/application.properties
Labels: back-end, api

#32 request: development <- 31 readme create
  .github/ISSUE_TEMPLATE/use-case---functionality.md
  README.md
Labels: documentation

#52 request: development <- 51 db enable cross origin requests cors
  src/main/java/com/noroff/mefit/config/CORSFilterConfig.java
  src/main/java/com/noroff/mefit/config/ConfigSettings.java
Labels: back-end, api

#59 request: development <- 57 fix minor issues annotations
  build.gradle
  src/main/java/com/noroff/mefit/config/DataSourceConfig.java
  src/main/java/com/noroff/mefit/data/controller/AddressController.java
  src/main/java/com/noroff/mefit/data/controller/ExerciseController.java
  src/main/java/com/noroff/mefit/data/controller/ProfileController.java
  src/main/java/com/noroff/mefit/data/controller/SetController.java
  src/main/java/com/noroff/mefit/data/controller/UserController.java
  src/main/java/com/noroff/mefit/data/controller/WorkoutController.java
  src/main/java/com/noroff/mefit/data/model/Address.java
  src/main/java/com/noroff/mefit/data/model/Exercise.java
  src/main/java/com/noroff/mefit/data/model/Profile.java
  src/main/java/com/noroff/mefit/data/model/Set.java
  src/main/java/com/noroff/mefit/data/model/User.java
  src/main/java/com/noroff/mefit/data/model/Workout.java
  src/main/java/com/noroff/mefit/data/repository/AddressRepository.java
  src/main/java/com/noroff/mefit/data/repository/ExerciseRepository.java
  src/main/java/com/noroff/mefit/data/repository/ProfileRepository.java
  src/main/java/com/noroff/mefit/data/repository/SetRepository.java
  src/main/java/com/noroff/mefit/data/repository/UserRepository.java
  src/main/java/com/noroff/mefit/data/repository/WorkoutRepository.java
  src/main/java/com/noroff/mefit/data/service/AddressService.java
  src/main/java/com/noroff/mefit/data/service/ExerciseService.java
  src/main/java/com/noroff/mefit/data/service/ProfileService.java
  src/main/java/com/noroff/mefit/data/service/SetService.java
  src/main/java/com/noroff/mefit/data/service/UserService.java
  src/main/java/com/noroff/mefit/data/service/WorkoutService.java
  src/main/java/com/noroff/mefit/model/type/WorkoutType.java
  src/main/java/com/noroff/mefit/repository/AddressRepository.java
  src/main/java/com/noroff/mefit/repository/ExerciseRepository.java
  src/main/java/com/noroff/mefit/repository/ProfileRepository.java
  src/main/java/com/noroff/mefit/repository/SetRepository.java
  src/main/java/com/noroff/mefit/repository/UserRepository.java
  src/main/java/com/noroff/mefit/security/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: bug, back-end, api, database, !important

#86 request: development <- 67 api default application responses
  src/main/java/com/noroff/mefit/config/ConfigSettings.java
  src/main/java/com/noroff/mefit/data/controller/AddressController.java
  src/main/java/com/noroff/mefit/data/controller/ExerciseController.java
  src/main/java/com/noroff/mefit/data/controller/GoalController.java
  src/main/java/com/noroff/mefit/data/controller/GoalWorkoutController.java
  src/main/java/com/noroff/mefit/data/controller/ProfileController.java
  src/main/java/com/noroff/mefit/data/controller/ProgramController.java
  src/main/java/com/noroff/mefit/data/controller/ProgramWorkoutController.java
  src/main/java/com/noroff/mefit/data/controller/SetController.java
  src/main/java/com/noroff/mefit/data/controller/UserController.java
  src/main/java/com/noroff/mefit/data/controller/WorkoutController.java
  src/main/java/com/noroff/mefit/data/model/Address.java
  src/main/java/com/noroff/mefit/data/model/DefaultResponse.java
  src/main/java/com/noroff/mefit/data/model/Exercise.java
  src/main/java/com/noroff/mefit/data/model/Goal.java
  src/main/java/com/noroff/mefit/data/model/GoalWorkout.java
  src/main/java/com/noroff/mefit/data/model/Profile.java
  src/main/java/com/noroff/mefit/data/model/Program.java
  src/main/java/com/noroff/mefit/data/model/ProgramWorkout.java
  src/main/java/com/noroff/mefit/data/model/Set.java
  src/main/java/com/noroff/mefit/data/model/User.java
  src/main/java/com/noroff/mefit/data/model/Workout.java
  src/main/java/com/noroff/mefit/data/repository/GoalWorkoutRepository.java
  src/main/java/com/noroff/mefit/data/repository/ProgramRepository.java
  src/main/java/com/noroff/mefit/data/repository/ProgramWorkoutRepository.java
  src/main/java/com/noroff/mefit/data/service/AddressService.java
  src/main/java/com/noroff/mefit/data/service/ExerciseService.java
  src/main/java/com/noroff/mefit/data/service/GoalService.java
  src/main/java/com/noroff/mefit/data/service/GoalWorkoutService.java
  src/main/java/com/noroff/mefit/data/service/ProfileService.java
  src/main/java/com/noroff/mefit/data/service/ProgramService.java
  src/main/java/com/noroff/mefit/data/service/ProgramWorkoutService.java
  src/main/java/com/noroff/mefit/data/service/SetService.java
  src/main/java/com/noroff/mefit/data/service/UserService.java
  src/main/java/com/noroff/mefit/data/service/WorkoutService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: bug, back-end, api, database

#89 request: development <- 88 fix program ignore workout
  src/main/java/com/noroff/mefit/data/model/Program.java
  src/main/java/com/noroff/mefit/data/service/GoalService.java
  src/main/java/com/noroff/mefit/data/service/ProgramService.java
Labels: bug, back-end, api

#91 request: development <- 90 fix addupdate relationships between data
  src/main/java/com/noroff/mefit/data/controller/AddressController.java
  src/main/java/com/noroff/mefit/data/controller/ProfileController.java
  src/main/java/com/noroff/mefit/data/controller/UserController.java
  src/main/java/com/noroff/mefit/data/model/Address.java
  src/main/java/com/noroff/mefit/data/model/DefaultResponse.java
  src/main/java/com/noroff/mefit/data/model/Exercise.java
  src/main/java/com/noroff/mefit/data/model/Profile.java
  src/main/java/com/noroff/mefit/data/model/Set.java
  src/main/java/com/noroff/mefit/data/service/AddressService.java
  src/main/java/com/noroff/mefit/data/service/ProfileService.java
  src/main/java/com/noroff/mefit/data/service/UserService.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: back-end, api, database
